### ISSUE TITLE
Missing pyOpenSSL

### ISSUE THREAD

**Issue by ning42** [sgtsquiggs/docker-plexpy#1]
When trying to enable SSL the following error occurs
```
2017-05-07 01:09:41 - WARNING :: MainThread : The pyOpenSSL module is missing. Install this module to enable HTTPS. HTTPS will be disabled.
```

**Comment by sgtsquiggs** [comment]
Hmm I don't use SSL in this image myself, i use a reverse proxy. I'll get this working.

**Comment by sgtsquiggs** [comment]
Try the latest build? It's working for me.

**Comment by ning42** [comment]
works perfectly - I really appreciate this - thanks @sgtsquiggs :)
